services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault-dev
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "8200:8200"
    # Executa diretamente o binário do Vault em modo servidor com o HCL montado
    command: ["vault", "server", "-config=/vault/config/vault.hcl", "-log-level=debug"]
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - vault-data-dev:/vault/file
    # NÃO definir environment aqui (evita herdar VAULT_LOCAL_CONFIG indesejado)

volumes:
  vault-data-dev:
