version: "3.9"

networks:
  net-vault-dev:
    name: net-vault-dev

volumes:
  vault-data-dev:
  vault-audit-dev:

services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault-dev
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://vault:8200"
      VAULT_CLUSTER_ADDR: "http://vault:8201"
      VAULT_UI: "true"
    ports:
      - "8200:8200"
    command: ["server", "-config=/vault/config/vault.hcl"]
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - vault-data-dev:/vault/file
      - vault-audit-dev:/vault/audit
    networks:
      - net-vault-dev
