services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault-dev
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"           # pode manter
      VAULT_API_ADDR: "http://vault:8205"         # <— alinhar com vault.hcl
      VAULT_CLUSTER_ADDR: "http://vault:8201"
      VAULT_UI: "true"
    ports:
      - "8200:8205"                               # <— host 8200 → contêiner 8205
    command: ["server", "-config=/vault/config/vault.hcl"]
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro
      - vault-data-dev:/vault/file
      - vault-audit-dev:/vault/audit

  caddy:
    image: caddy:2
    container_name: vault-proxy
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN}
      ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - net-vault
    depends_on:
      - vault

networks:
  net-vault:
    name: net-vault

volumes:
  vault-data:
  vault-audit:
  caddy-data:
  caddy-config:
